import { z } from 'zod';

export const leadFormSchema = z.object({
  name: z.string().optional(),
  first_name: z.string().optional(),
  middle_name: z.string().optional(),
  last_name: z.string().optional(),
  offer: z.string().optional(),
  agent_name: z.string().optional(),
  status: z.string().optional(),
  reason: z.string().optional(),
  age: z.union([z.string(), z.number()])
    .optional(),
  gender: z.string().optional(),
  lead_source: z.string().optional(),
  mobile_phone: z.string().optional(),
  booking_phone_number: z.string().optional(),
  home_phone: z.string().optional(),
  address_1: z.string().optional(),
  source_campaign: z.string().min(1, 'Source is required'),

  activity_code: z.string().optional(),
  call_sub_result: z.string().optional(),
  will_call_us_again_reason: z.string().optional(),
  not_interested_reason: z.string().optional(),
  inquiry_only_reason: z.string().optional(),
  injection_date: z.string().optional(),
  duplicate_lead: z.string().optional(),
  call_count: z.union([z.string(), z.number()])
    .optional(),
  modified_by: z.string().optional(),
  patient_id: z.string().optional(),
  phonecall_patient_id: z.string().optional(),
  description: z.string().optional(),
  first_call_time: z.string().optional(),
  last_call_result: z.string().optional(),
  last_call_total_duration: z.union([z.string(), z.number()]).optional(),
  last_phone: z.string().optional(),
  last_call_created_by: z.string().optional(),
  booking_count: z.union([z.string(), z.number()]).optional(),
  reservation_date_1: z.string().optional(),
  doctor1: z.string().optional(),
  notes: z.string().optional(),
  ads: z.string().optional(),
  ad_set: z.string().optional(),
  no_show_lost_reason: z.string().optional(),
  specialtie_1: z.string().optional(),
  specialtie_2: z.string().optional(),
  specialtie_3: z.string().optional(),
  ads_name: z.string().optional(),
  modified_on: z.string().optional(),
  created_by: z.string().optional(),
  event_agent_name: z.string().optional(),
  communication_channel: z.string().min(1, 'Communication Channel is required'),

  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

export type LeadFormInput = z.infer<typeof leadFormSchema>;
