import { routes } from '@/config/routes';
import { DUMMY_ID } from '@/config/constants';
import {
  PiCirclesThreePlusFill,
  PiCircleFill,
  PiCirclesFourFill,
  PiShoppingCartDuotone,
  PiHeadsetDuotone,
  PiPackageDuotone,
  PiChartBarDuotone,
  PiFileImageDuotone,
  PiCurrencyDollarDuotone,
  PiSquaresFourDuotone,
  PiGridFourDuotone,
  PiFeatherDuotone,
  PiChartLineUpDuotone,
  // PiImageDuotone,
  PiMapPinLineDuotone,
  PiUserGearDuotone,
  PiBellSimpleRingingDuotone,
  PiUserDuotone,
  PiEnvelopeSimpleOpenDuotone,
  PiStepsDuotone,
  PiCreditCardDuotone,
  PiStackDuotone,
  PiTableDuotone,
  PiBrowserDuotone,
  PiBoundingBoxDuotone,
  PiHourglassSimpleDuotone,
  PiUserCircleDuotone,
  PiShootingStarDuotone,
  PiRocketLaunchDuotone,
  PiFolderLockDuotone,
  PiBinocularsDuotone,
  PiHammerDuotone,
  PiNoteBlankDuotone,
  PiUserPlusDuotone,
  PiShieldCheckDuotone,
  PiLockKeyDuotone,
  PiChatCenteredDotsDuotone,
  PiMagicWandDuotone,
  PiCalendarPlusDuotone,
  PiListChecks,
  PiBuildingsFill,
  PiShoppingCartSimple,
  PiStorefront,
  PiRoadHorizon,
  PiSquareHalf,
  PiChartBar,
  PiCubeFocusThin,
  PiFinnTheHuman,
  PiCircleDashedBold,
  PiPhoneCall,
  PiUserCircle,
  PiMapPinDuotone,
  PiGearDuotone,
  PiGlobe,
  PiReceipt,
} from 'react-icons/pi';
import { IoWarningOutline,IoNotificationsSharp, IoBusiness, IoPeopleOutline, IoHelpCircleOutline, IoStarOutline, IoInformationCircleOutline, IoChatboxEllipsesOutline, IoCardOutline, IoDownloadOutline, IoMedicalOutline, IoConstructOutline, IoHelpCircle  } from "react-icons/io5";
import { FaUserShield } from "react-icons/fa6";
import { TbUserShield } from "react-icons/tb";
import { RiUserStarLine } from "react-icons/ri";
import { BsPinMapFill } from 'react-icons/bs';


// Note: do not add href in the label object, it is rendering as label
export const menuItemsHaydrogen = [
  { name: 'Home' },

  {
    name: 'Dashboard',
    href: '/',
    permissions: 'dashboard', // optional custom
    icon: <PiChartBar />,
  },

  { name: 'Home Management' },
  {
    name: 'Hero Section',
    nameAr: 'من نحن',
    href: '/attachments?section_id=12',
    icon: <IoStarOutline />,
    permissions: 'attachments',
  },
  {
    name: 'Our Services',
    nameAr: 'من نحن',
    href: '/attachments?section_id=1',
    icon: <IoConstructOutline />,
    permissions: 'attachments',
  },
  {
    name: 'About Home Healers',
    nameAr: 'من نحن',
    href: '/attachments?section_id=2',
    icon: <IoInformationCircleOutline />,
    permissions: 'attachments',
  },
  {
    name: 'Where is the pain?',
    nameAr: 'من نحن',
    href: '/attachments?section_id=3',
    icon: <IoMedicalOutline />,
    permissions: 'attachments',
  },
  {
    name: 'Download the app',
    nameAr: 'من نحن',
    href: '/attachments?section_id=4',
    icon: <IoDownloadOutline />,
    permissions: 'attachments',
  },
  {
    name: 'Request a medical card',
    nameAr: 'من نحن',
    href: '/attachments?section_id=5',
    icon: <IoCardOutline />,
    permissions: 'attachments',
  },
  {
    name: 'Do you have any questions? Contact us',
    nameAr: 'من نحن',
    href: '/attachments?section_id=6',
    icon: <IoChatboxEllipsesOutline />,
    permissions: 'attachments',
  },

  { name: 'About Management' },
  {
    name: 'About Home Healers',
    nameAr: 'من نحن',
    href: '/attachments?section_id=7',
    icon: <IoInformationCircleOutline />,
    permissions: 'attachments',
  },
  {
    name: 'Why Home Healers?',
    nameAr: 'من نحن',
    href: '/attachments?section_id=8',
    icon: <IoStarOutline />,
    permissions: 'attachments',
  },
  {
    name: 'Best Physical Therapists',
    nameAr: 'من نحن',
    href: '/attachments?section_id=9',
    icon: <IoPeopleOutline />,
    permissions: 'attachments',
  },

  { name: 'Social Management' },
  {
    name: 'Faqs',
    nameAr: 'من نحن',
    href: '/faqs',
    icon: <IoHelpCircle />,
    permissions: 'faqs',
  },
  {
    name: 'Blogs',
    nameAr: 'من نحن',
    href: '/blogs',
    icon: <IoBusiness />,
    permissions: 'blogs',
  },
  {
    name: 'Frequently Asked Questions',
    nameAr: 'من نحن',
    href: '/attachments?section_id=10',
    icon: <IoHelpCircleOutline />,
    permissions: 'attachments',
  },

  { name: 'Partners Management' },
  {
    name: 'Our Partners',
    nameAr: 'من نحن',
    href: '/attachments?section_id=11',
    icon: <IoPeopleOutline />,
    permissions: 'attachments',
  },
  {
    name: 'Client Review',
    nameAr: 'من نحن',
    href: '/client-review',
    icon: <IoStarOutline />,
    permissions: 'clients',
  },

  { name: 'User Mangement ' },
  {
    name: 'Permissions',
    href: routes.permissions.index,
    permissions: 'permissions',
    icon: <PiUserGearDuotone />,
  },
  {
    name: 'Roles',
    href: routes.roles.index,
    icon: <PiPackageDuotone />,
    permissions: 'roles',
  },
  {
    name: 'Users',
    href: routes.users.index,
    icon: <FaUserShield />,
    permissions: 'users',
  },

  { name: 'master Mangement ' },
  {
    name: 'Countries',
    href: routes.countries.index,
    icon: <PiMapPinLineDuotone />,
    permissions: 'countries',
  },
  {
    name: 'Cities',
    href: routes.cities.index,
    icon: <PiBuildingsFill />,
    permissions: 'cities',
  },
  {
    name: 'Addresses',
    href: routes.addresses.index,
    icon: <PiMapPinDuotone />,
    permissions: 'addresses',
  },
  {
    name: 'States',
    href: routes.states.index,
    icon: <BsPinMapFill />,
    permissions: 'state',
  },
  {
    name: 'coupons',
    href: routes.coupons.index,
    icon: <PiListChecks />,
    permissions: 'coupons',
  },
  {
    name: 'packages',
    href: routes.packages.index,
    icon: <PiCreditCardDuotone />,
    permissions: 'packages',
  },
  {
    name: 'customer-supports',
    href: routes.customerSupport.index,
    icon: <PiPhoneCall />,
    permissions: 'customer_supports',
  },
  {
    name: 'Patients',
    href: routes.patients.index,
    icon: <PiCircleDashedBold />,
    permissions: 'patients',
  },
  {
    name: 'Doctors',
    href: routes.doctors.index,
    icon: <PiUserCircle />,
    permissions: 'doctors',
  },
  {
    name: 'categories',
    href: routes.mainCategories.index,
    icon: <PiListChecks />,
    permissions: 'categories',
  },
  {
    name: 'Services',
    href: routes.services.index,
    icon: <PiRoadHorizon />,
    permissions: 'services',
  },
  {
    name: 'Nationalities',
    href: routes.nationalities.index,
    icon: <PiHammerDuotone />,
    permissions: 'nationalities',
  },
    {
    name: 'Invoices',
    href: routes.invoices.index,
    icon: <PiReceipt />,
    permissions: 'invoices',
  },
  {
    name: 'reservations',
    href: routes.reservations.index,
    icon: <PiGlobe />,
    permissions: 'reservations',
  },


  { name: 'Settings Mangement ' },
  {
    name: 'Settings',
    href: routes.settings.index,
    icon: <PiGearDuotone />,
    permissions: 'settings',
  }
  // { name: 'product Mangement ' },
  // {
  //   name: 'Products',
  //   href: routes.products.index,
  //   icon: <PiCubeFocusThin />,
  //   permissions: 'products',
  // },
  // {
  //   name: 'Brands',
  //   href: routes.brands.index,
  //   icon: <PiGridFourDuotone />,
  //   permissions: 'brands',
  // },
  // {
  //   name: 'Features',
  //   href: routes.features.index,
  //   icon: <PiFeatherDuotone />,
  //   permissions: 'features',
  // },
  // {
  //   name: 'Features Categories',
  //   href: routes.features_categories.index,
  //   icon: <PiSquaresFourDuotone />,
  //   permissions: 'features_categories',
  // },
];

